"""empty message

Revision ID: de10779fd69e
Revises: 05cb711499c9
Create Date: 2018-04-10 16:29:01.301778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de10779fd69e'
down_revision = '05cb711499c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock')
    op.drop_column('products', 'price')
    # ### end Alembic commands ###
